### ISSUE TITLE
[FEATURE REQUEST] Add description/information on Modules tab

### ISSUE THREAD

**Issue by Cx01N** [BC-SECURITY/Starkiller#11]
**Is your feature request related to a problem? Please describe.**
The current modules page does not all you to view the information about modules without going to an active agent.

**Describe the solution you'd like**
Add the module description/information to the modules page to match how 'execute module' displays the info.

Modules Tab:
![image](https://user-images.githubusercontent.com/20302208/79034255-64bb4b00-7b69-11ea-8008-7476132cff55.png)

Execute Modules:
![image](https://user-images.githubusercontent.com/20302208/79034231-4bb29a00-7b69-11ea-9086-6d962f0a697b.png)

**Describe alternatives you've considered**
The current implementation works, but it would definitely make it easier to use the modules page as a reference section.

**Additional context**
N/A

**Comment by logicsec-zz** [comment]
Could this maybe be done with a column selector? Something like a simple drop-down box where you can select the visible columns.

**Comment by Cx01N** [comment]
@logicsec Yeah, I think clicking on the module and having it expand to show that info would work. Is that what you had in mind?

**Comment by vinnybod** [comment]
I imagine 3 routes:
1. Dynamic columns as @logicsec suggested. You'd be able to pick which column you want to view in the table. I worry that this might be hard to display longer columns like "description".
2. A drawer similar to the rest of the sections. This would eliminate the need to implement it later if we add actionable items to the module view, but is overkill for right now.
3. Using el-table's [expandable row](https://element.eleme.io/#/en-US/component/table#table) feature. This is the implementation I think I like best.
<img width="875" alt="Screen Shot 2020-04-12 at 10 22 07 AM" src="https://user-images.githubusercontent.com/9831420/79075393-6c810980-7ca7-11ea-82cb-f0741b802597.png">

**Comment by logicsec-zz** [comment]
Pushed an initial PR for the view of the description of the module. @vinnybod I can probably clean this up later using your expandable row feature?

**Comment by vinnybod** [comment]
@logicsec thanks for the PR, btw did you put that template in yourself? I don't remember configuring a PR template for the repo.

As for the contents of it. The descriptions don't look too bad in the table, most are much shorter than I expected them to be! What do you think about doing the expandable rows though? Given that we could fit in "Comments" and "Authors" as well and I don't think we would necessarily need to sort by them.

**Comment by logicsec-zz** [comment]
I did put that in. Just wanted to make sure I had some sort of template to go off of. 
 As for the expandable rows go, I am going to take a look at that tonight and see how that goes. I can just push them to the same branch/PR I have for this I think if you are fine with that?

**Comment by vinnybod** [comment]
Yeah same branch sounds good :+1:

**Comment by logicsec-zz** [comment]
Pushed the commit to convert to expandabe rows. It works but I think I want to clean up the nested objects a little better. Let me know if that works?
