### ISSUE TITLE
[FEATURE REQUEST] Indicator of Elevated Process in Agents 

### ISSUE THREAD

**Issue by Hubbl3** [BC-SECURITY/Starkiller#19]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When an agent is displayed in the agents dash board it showed provide an indicator of whether or not it is running in a high integrity process.  

**Describe alternatives you've considered**

**Additional context**

**Comment by vinnybod** [comment]
Closed by https://github.com/BC-SECURITY/Starkiller/releases/tag/v1.2.0
