### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by JustAFriendlyCat** [BC-SECURITY/Starkiller#23]
**Empire Version**
- 3.2.0 BC-Security Fork

**Starkiller Version**
1.2.0

**OS Information (Linux flavor, Python version)**
- OS: Windows 10 Pro N
- Python: Python 3.8.2

**Describe the bug**
The slider bar thingy's on agent console keeps disappearing and appearing.

**To Reproduce**
1. Install Starkiller V1.2.0
2. Create a listener
3. Create a stager
4. Run Stager on desired target.
5. Click Target and you will see the slider bar thingy's disappearing and appearing

**Expected behavior**
Slider's should remain appeared

**Screenshots**
![ezgif-6-62699c1196d5](https://user-images.githubusercontent.com/41790044/80845339-2fa29580-8c09-11ea-9ee1-ccdf072cef83.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 Pro N
 - Version [e.g. 22] 1909

**Additional context**
I like the application and i think you have done amazing work in the 2 months it's been here

**Comment by vinnybod** [comment]
Ah yeah I'm seeing that I messed something up just before the 1.2.0 release. That loading icon should disappear after the initial load as well.

**Comment by vinnybod** [comment]
This should be fixed in 1.2.1. I don't have a windows machine nearby to test it, but I had the same behavior in macOS. If it isn't fixed feel free to reopen.
