### ISSUE TITLE
[FEATURE REQUEST] - Make it 100% offline

### ISSUE THREAD

**Issue by b4b857f6ee** [BC-SECURITY/Starkiller#34]
**Is your feature request related to a problem? Please describe.**
Yes, the GUI need some external source to work like google font

![image](https://user-images.githubusercontent.com/36012515/84990078-e79dea80-b144-11ea-915b-a76fed185a14.png)

**Describe the solution you'd like**
Use only local font and link, don't depend on internet ressources

**Describe alternatives you've considered**

**Additional context**
I'm on 1.2.3 Ubuntu 18.04

**Comment by b4b857f6ee** [comment]
![image](https://user-images.githubusercontent.com/36012515/84994804-86c5e080-b14b-11ea-9d59-6a2697455f81.png)

**Comment by vinnybod** [comment]
I believe I covered everything in 1.2.4.... if you run into anything else that calls out to the internet, let me know.
