### ISSUE TITLE
[BUG] Cannot see adding listener

### ISSUE THREAD

**Issue by b4b857f6ee** [BC-SECURITY/Starkiller#35]
**Empire Version**
- Empire 3.2.3

**Starkiller Version**
1.2.3

**OS Information (Linux flavor, Python version)**
- OS: Ubuntu 18.04
- Python: Python3

**Describe the bug**
Starting Empire with --rest with specific password and username
Starting starkiller
loggin on Starkiller
Create a Listener, work but i can see it in the Starkiller.
This is the error in the dev mode of starkiller
![image](https://user-images.githubusercontent.com/36012515/84993495-a0662880-b149-11ea-841f-2ccc36b37588.png)

**To Reproduce**
1. Go to 'Empire folder 3.2.3 and start it as root with ./empire --rest --username admin --password 'Password123!''
2. Start in other console as root starkiller './starkiller... --no-sandbox (i test with and without the option no change)'
3. Log on Starkiller webui
4. Create a Listener http and return in the Listener menu, i can't see any listener but in the console of the empire cli you can see the listener.

**Expected behavior**
See the listener running in the Starkiller menu

**Screenshots**
Accessing the Listener menu 
![image](https://user-images.githubusercontent.com/36012515/84995058-d73d3e00-b14b-11ea-8bf4-65d5e3457cef.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04

**Additional context**
Offline VM

**Comment by vinnybod** [comment]
I haven't been able to reproduce this so far. We definitely need to fix the error message displays... Can you check your network request tab and see what the body of the response for the listener POST says?

**Comment by b4b857f6ee** [comment]
@vinnybod Sure!

I have 2 requests by pressing the 'CREATE'

First
![image](https://user-images.githubusercontent.com/36012515/85671503-3823c380-b6c2-11ea-8742-54e6964832f5.png)
![image](https://user-images.githubusercontent.com/36012515/85671529-407bfe80-b6c2-11ea-86d6-7c710697ba3b.png)
![image](https://user-images.githubusercontent.com/36012515/85671569-4bcf2a00-b6c2-11ea-9f73-db7bb4d5adc7.png)

Second
![image](https://user-images.githubusercontent.com/36012515/85671678-67d2cb80-b6c2-11ea-8461-cb3a79151ac6.png)
![image](https://user-images.githubusercontent.com/36012515/85671742-78834180-b6c2-11ea-8abe-ba85698dc2da.png)


And this is what is get when clicking on Listener, so the problem is here
![image](https://user-images.githubusercontent.com/36012515/85671966-b54f3880-b6c2-11ea-862a-4e28ff1ec089.png)
![image](https://user-images.githubusercontent.com/36012515/85672018-c0a26400-b6c2-11ea-8788-4415605856ac.png)
![image](https://user-images.githubusercontent.com/36012515/85672070-cb5cf900-b6c2-11ea-9024-c7e5904ced16.png)
![image](https://user-images.githubusercontent.com/36012515/85672286-06f7c300-b6c3-11ea-86d3-a3d8955a5210.png)

**Comment by vinnybod** [comment]
hey @b4b857f6ee, first off thank you for all the detailed screenshots! It was super helpful! 🙏

So after looking into this a bit more, I believe that the solution is that you need to run Empire with at least Python 3.7. The reason is that `fromisoformat` was [added in Python 3.7.](https://docs.python.org/3/library/datetime.html#datetime.date.fromisoformat) and is used in [Empire v3.2.3](https://github.com/BC-SECURITY/Empire/pull/224/files#diff-d6023fdb83357dc59f3384315093af77R59) for the timestamp fixes.

**Comment by b4b857f6ee** [comment]
You'r very welcome.

I have python 3.7, 3..8 on my system.
the empire file have :
![image](https://user-images.githubusercontent.com/36012515/85835066-bb154e80-b794-11ea-8703-e5074906315e.png)

![image](https://user-images.githubusercontent.com/36012515/85837949-147f7c80-b799-11ea-92bd-8b46c3ad569b.png)
I have to try how to force pip to install not flask for python3.6 (which is what i have) but the version for python3.7

**Comment by b4b857f6ee** [comment]
I manage to install most of it with 
![image](https://user-images.githubusercontent.com/36012515/85839068-bf446a80-b79a-11ea-8315-346bf93ebd4d.png)

But this one netifaces
![image](https://user-images.githubusercontent.com/36012515/85839105-ca979600-b79a-11ea-9171-b5fe1597a8d7.png)

Don't have python 3.7 :/
https://pypi.org/project/netifaces/

**Comment by vinnybod** [comment]
The dependency management side of Python is definitely a weakness for me, but I think there is some conflict due to having python3.6 and 3.7 at the same time. I was able to reproduce your empire dependency issue in Ubuntu having multiple versions of python3 on the machine. Once I ran Empire in a 3.7 virtual environment using pipenv, it worked.

**Comment by b4b857f6ee** [comment]
Ok, i run it on the kali and i can see the Listeners :).
