### ISSUE TITLE
use starkiller client but there's a 500 error on empire restful api

### ISSUE THREAD

**Issue by J0o1ey** [BC-SECURITY/Starkiller#4]
Dear author
 I use empire3.1.1 on my server
Using command "./empire --rest --username admin password admin" to create a teamserver
But when I use starkiller client on my windows(admin,admin) to connect to empire restful api
There is a 500 error on the empire restfulapi output,and there is no change on  Starkiller's Initial interface(even no error,just stay in the initial stauts)
If you're available to help me, I will feel much honored

**Comment by vinnybod** [comment]
Please update your issue to use the issue template. It's meant to get all the information out in the open to save everyone time.

With that said looking at your command, you aren't setting the password properly.
`./empire --rest --username admin --password password`

If you continue to get 500s, open the developer console in starkiller to get the endpoint and any message included in the response.

**Comment by tyraniter** [comment]
I met the same question and i found the reason.
The user login api query the password in db with the sql ""SELECT password from users WHERE username = ? AND enabled = true LIMIT 1" in lib/common/user.py,but the value of "enable" in db is 1,so the server throw an exception of "{"error":"OperationalError('no such column: true',)"}" with error code 500

**Comment by J0o1ey** [comment]
Thanks for a lot,sir

haha,Where are you from？Are you a red teamer？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tyraniter"<notifications@github.com&gt;; 
发送时间: 2020年3月13日(星期五) 中午11:36
收件人: "BC-SECURITY/Starkiller"<Starkiller@noreply.github.com&gt;; 
抄送: "J0o1ey’"<547006660@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [BC-SECURITY/Starkiller] use starkiller client but there&#39;s a 500 error on empire restful api (#4)





 
I met the same question and i found the reason.
 The user login api query the password in db with the sql ""SELECT password from users WHERE username = ? AND enabled = true LIMIT 1" in lib/common/user.py,but the value of "enable" in db is 1,so the server throw an exception of "{"error":"OperationalError('no such column: true',)"}" with error code 500

**Comment by vinnybod** [comment]
Hey @tyraniter thanks for tracking it down! This is tied to older versions for SQLite and will be fixed in 3.1.2 of Empire. Until that release is cut, you can run the dev branch of Empire.

Empire PR: https://github.com/BC-SECURITY/Empire/pull/120

**Comment by tyraniter** [comment]
> Thanks for a lot,sir haha,Where are you from？Are you a red teamer？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "tyraniter"<notifications@github.com&gt;; 发送时间: 2020年3月13日(星期五) 中午11:36 收件人: "BC-SECURITY/Starkiller"<Starkiller@noreply.github.com&gt;; 抄送: "J0o1ey’"<547006660@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [BC-SECURITY/Starkiller] use starkiller client but there&#39;s a 500 error on empire restful api (#4) I met the same question and i found the reason. The user login api query the password in db with the sql ""SELECT password from users WHERE username = ? AND enabled = true LIMIT 1" in lib/common/user.py,but the value of "enable" in db is 1,so the server throw an exception of "{"error":"OperationalError('no such column: true',)"}" with error code 500 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I'm from China.I guess you are Chinese,too.

**Comment by J0o1ey** [comment]
哈哈，兄弟能留个联系方式嘛，认识一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tyraniter"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月13日(星期五) 下午2:58
收件人:&nbsp;"BC-SECURITY/Starkiller"<Starkiller@noreply.github.com&gt;;
抄送:&nbsp;"J0o1ey’"<547006660@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [BC-SECURITY/Starkiller] use starkiller client but there's a 500 error on empire restful api (#4)





  
Thanks for a lot,sir haha,Where are you from？Are you a red teamer？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "tyraniter"<notifications@github.com&gt;; 发送时间: 2020年3月13日(星期五) 中午11:36 收件人: "BC-SECURITY/Starkiller"<Starkiller@noreply.github.com&gt;; 抄送: "J0o1ey’"<547006660@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [BC-SECURITY/Starkiller] use starkiller client but there's a 500 error on empire restful api (#4) I met the same question and i found the reason. The user login api query the password in db with the sql ""SELECT password from users WHERE username = ? AND enabled = true LIMIT 1" in lib/common/user.py,but the value of "enable" in db is 1,so the server throw an exception of "{"error":"OperationalError('no such column: true',)"}" with error code 500 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
I'm from China.I guess you are Chinese,too.
