### ISSUE TITLE
[BUG] Error 400 when creating new listener

### ISSUE THREAD

**Issue by ZkClown** [BC-SECURITY/Starkiller#5]
**Empire Version**
- Empire 3.1.2

**Starkiller Version**
1.0.0. Rebuilded it from source

**OS Information (Linux flavor, Python version)**
- OS: Debian 10
- Python: python3.7

**Describe the bug**
When we attempt to create a new listener that is not an http listener, we obtain 400 error. This is due to the file: src/api/listener-api.js.
We can see in the code that the function which handles the listener creation is createListener(). This function always requests the URI "/listeners/http".
However when we look at Empire's code we have the API endpoint to create a listener: "@app.route('/api/listeners/<string:listener_type>', methods=['POST'])". Therefore, the URI requested in Starkiller should have been something like "listeners/$type"  

**To Reproduce**
Create a Listener that is not "http"

**Expected behavior**
Create the good listener

**Screenshots**
![image](https://user-images.githubusercontent.com/18192211/77099490-523f6d00-6a14-11ea-9015-176b959a6e90.png)
The screenshot show the 400 error when attempting to create a listeners.
The values displayed are some debug print used to find the problem.

**Desktop (please complete the following information):**

**Additional context**
The workaround is to create through CLI or directly with the API to create the listener
Best regards,

**Comment by vinnybod** [comment]
Thanks for the detailed issue! this will be in 1.0.1
