### ISSUE TITLE
[BUG] Unable to create more than 1 'redirector' listener

### ISSUE THREAD

**Issue by SaltyWafffles** [BC-SECURITY/Starkiller#53]
**Empire Version**
- Empire 3.5.1

**Starkiller Version**
- Starkiller 1.4.0

**OS Information (Linux flavor, Python version)**
- OS: Kali 2020.3
- Python: 3.8.6

**Describe the bug**
I am unable to start more than one 'redirector' listener at one time. Prevents pivoting through more than a single end-target. When attempting to make an additional 'redirector' listener, Suspect this is similar to my previous ticket with Empire not being able to do the same thing: https://github.com/BC-SECURITY/Empire/issues/386

**To Reproduce**
1. Get an agent on a machine
2. Setup a 'redirector' listener
3. PSexec to another target, calling back to your 'redirector' listener
4. Attempt to setup another 'redirector' listener on your new target box
Error / failure condition should trigger when attempting to setup the new 'redirector' listener

**Expected behavior**
I should be able to set up additional 'redirector' listeners on subsequent targets to pivot more than 1 target deep in a network.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by vinnybod** [comment]
I see this was fixed in Empire https://github.com/BC-SECURITY/Empire/issues/386. Does it still persist in Empire 3.6.2 with Starkiller?

**Comment by SaltyWafffles** [comment]
Sorry, Starkiller with Empire 3.6.2 is working. I must have been using the old version.
