### ISSUE TITLE
[BUG] RunAs / SpawnAs / Credential Use failure

### ISSUE THREAD

**Issue by SaltyWafffles** [BC-SECURITY/Starkiller#56]
**Empire Version**
- Empire 3.5.1

**Starkiller Version**
Starkiller 1.4.0

**OS Information (Linux flavor, Python version)**
- OS: Kali 2020.3
- Python: 3.8.6

**Describe the bug**
Suspected that ALL credential modules are truncating any passwords with a '$' in them. Confirmed to be an issue with runas/spawnas, but I suspect its for all credential use.

**To Reproduce**
1. Get an agent on a machine
2. Attempt to use the 'runas' or 'spawnas' module with credentials that has a '$' in it
3. Cred use will fail

**Expected behavior**
Credentials should be able to be used successfully if a user has any special characters, specifically a $ sign in the password.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by vinnybod** [comment]
Closed since its a duplicate of https://github.com/BC-SECURITY/Empire/issues/409 (which I believe is fixed in 4.0)
