### ISSUE TITLE
[FEATURE REQUEST]  Web based frontend

### ISSUE THREAD

**Issue by tehseensagar** [BC-SECURITY/Starkiller#70]
**Is your feature request related to a problem? Please describe.**
It's awesome tools revive from dead :) . Could you please port it to web based front end  as we have in old empire.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cfuk** [comment]
That would be awesome!

**Comment by vinnybod** [comment]
Working on this for Starkiller 2.0 which will come out with Empire 5.0 later this year.

**Comment by vinnybod** [comment]
Starkiller 2.0 is now a web application packaged with Empire.
