### ISSUE TITLE
[BUG] QUESTION How to connect by browser

### ISSUE THREAD

**Issue by piedacoulisse2** [BC-SECURITY/Starkiller#73]
**Empire Version**
- Empire 4.5.5

**Starkiller Version**
1.1.0

**OS Information (Linux flavor, Python version)**
- OS: KALI (Starkiller/Empire) + Windows ( Web browser)
- Python: 3.9

**Describe the bug**
I try to connect to Starkiller by web browser but I obtain an 401 Unauthorise error

**To Reproduce**
1. Start Starkiller
2. Connect to https://IP:1337
3. Error 401 : Unauthorise

**Expected behavior**
Connexion page 

**Screenshots**
![image](https://user-images.githubusercontent.com/74360897/168241009-1c419223-5177-4b6e-96a5-575fe4b478e5.png)

**Desktop (please complete the following information):**
 - OS: KALI (Starkiller/Empire) + Windows ( Web browser)
 - Version 11

**Additional context**
none

**Comment by ghostpepper108** [comment]
I have Empire server on Kali and Starkiller on Windows 10, different systems. You are trying to access via browser which is not the correct way. Starkiller has its own interface. If you want to access from a Windows box then you need to install and run Starkiller on Windows (not from the browser)
