### ISSUE TITLE
vue-cli-service electron:serve  INFO  Starting development server... 40% building 77/84 modules 7 active ...js??vue-loader-options!/home/user/Documents/tools/Starkiller/node_modules/eslint-loader/index.js??ref--13-0!/home/user/Documents/tools/Starkiller/src/components/StarkillerSnackbar.vuenode: ../src/coroutine.cc:134: void* find_thread_id_key(void*): Assertion `thread_id_key != 0x7777' failed.

### ISSUE THREAD

**Issue by thecowmilk** [BC-SECURITY/Starkiller#77]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 3.x
Latest
## Starkiller Version
Latest, cloned from github

## OS Information (Linux flavor, Python version)
- OS: Kali Linux
- Python: python3(I also have python2.7)

## Describe the bug
Something not compiling using yarn

## To Reproduce
Clone https://github.com/BC-SECURITY/Starkiller repo
Then find a way to install nodejs 16x
Then follow the installation https://github.com/BC-SECURITY/Starkiller#build-and-run-from-source

## Expected behavior
It should compile without erros

## Screenshots
![image](https://user-images.githubusercontent.com/43875051/211329063-dea321d8-1ea2-4fc8-84b6-61d518b86629.png)

**Comment by vinnybod** [comment]
Starkiller is using Vite as of 2.0
