### ISSUE TITLE
Starkiller error GPU

### ISSUE THREAD

**Issue by SeeNanshaneisurely** [BC-SECURITY/Starkiller#78]
The latest version of kali, using the latest Starkiller error
The error message is shown in the figure::
![image](https://user-images.githubusercontent.com/57738442/213105403-5cc19875-0657-4e3e-a079-cdf8d31dbc1c.png)

**Comment by SeeNanshaneisurely** [comment]
```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[412349:0118/015948.275397:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
zsh: trace trap  ./starkiller-1.12.0.AppImage

```

**Comment by vinnybod** [comment]
Starkiller is no longer an Electron application as of 2.0
