### ISSUE TITLE
No starkiller in latest Kali

### ISSUE THREAD

**Issue by S0me1-dev** [BC-SECURITY/Starkiller#80]
========================================================================================
 [Version] 5.0.0-beta2 | [Web] https://github.com/BC-SECURITY/Empire
how to run starkiller gui? 

no starkiller in zsh in kali , no plugins etc. Cant find any info about it 
if i run apt install powershell-empire starkiller 
it just says that powershell empire allready newest version. help plz )
nothing can found in docs ) https://bc-security.gitbook.io/empire-wiki/interfaces/starkiller

**Comment by S0me1-dev** [comment]
https://www.youtube.com/watch?v=zFlsxrGMScE&t=167s

there is no *starkiller* in Kali in my system. latest kali 
└─# uname -r
6.1.0-kali5-amd64

└─# apt install powershell-empire
powershell-empire is already the newest version (5.0.4-0kali2).

└─# starkiller
starkiller: command not found

└─# apt install powershell-empire starkiller
Note, selecting 'powershell-empire' instead of 'starkiller'
powershell-empire is already the newest version (5.0.4-0kali2)

**Comment by vinnybod** [comment]
>As of Empire 5.0 and Starkiller 2.0, you no longer need to install Starkiller or build it from source. It is prepackaged in Empire as a submodule and served via Empire's API.

**Comment by S0me1-dev** [comment]
> > As of Empire 5.0 and Starkiller 2.0, you no longer need to install Starkiller or build it from source. It is prepackaged in Empire as a submodule and served via Empire's API.

@vinnybod finaly found him on locahost:port/index.html 

 but still cant rum him as gui in window - no 'starkiller' command (on default kali/ on git cloned)
